name: testing secret passing in workflow
on:  
  workflow_dispatch:
env:
  ACTION_STEP_DEBUG: true
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "checking scret varibale is visible or not"
        run: |
          echo "Sercret Value : ${{secrets.TEST_KET}}"
          ${{secrets.TEST_KET}}
